### ISSUE TITLE
Compile latest version

### ISSUE THREAD

**Issue by YellowZaki** [FreestyleCrafter/AIOJetpacks#5]
Can anyone compile the latest version of this plugin? I don't know how to do it.

**Comment by FreestyleCrafter** [comment]
[Updated Bukkit.org post](http://dev.bukkit.org/bukkit-plugins/aio-jetpacks/)

Still needs approval

You can also download it on [Spigotmc.org](https://www.spigotmc.org/resources/aio-jetpacks.4170/)
